### ISSUE TITLE
Add expect {} with coroutine support (suspend lambda)

### ISSUE THREAD

**Issue by tenor-dev** [robstoll/atrium#1180] opened 2022-08-25 08:05 UTC
*Platform* (all, jvm, js): all
*Extension* (none, kotlin 1.3): none

## Currently you need to write
```
expect { runBlocking { suspendFunction() }}.toThrow<Something>()
```

## It would be great to have suspending built-in:
```
coExpect { suspendFunction() }.toThrow<Something>()
```

"co" prefix is already used by mockk: coVerify() and coEvery(), so it will be familiar to developers.

coExpect function should be a suspend function itself, so it can be used inside of `runTest {}` from kotlinx-coroutines-test.

**Comment by robstoll** [comment] 2022-08-25 20:32
Thanks for the idea, I'll consider your suggestion in https://github.com/robstoll/atrium/issues/363.
Since this issue is a duplicate of it, I'll close this one. Please up-vote the other (react with :+1: on the issue description).
See https://github.com/robstoll/atrium/issues/363#issuecomment-582906691 for a function you could use until atrium provides something built in.
In case you have some spare time, then please read the discussion in the other issue and add your comment, thanks

**Closed by robstoll** 2022-08-25 20:32 UTC
