### ISSUE TITLE
Extra dependencies needed to be declared to work with Spek Framework Plugin (Android Studio / Intellij IDEA)

### ISSUE THREAD

**Issue by ultraon** [robstoll/atrium#827] opened 2021-03-01 21:38 UTC
*Affected Version*: 0.15.0 (and before)
*API*: fluent-en_GB
*Platform*: android
*Extension*: none

## How to reproduce the problem  
Consider the following code snippet
```kotlin
object TestSpekSpecification
    : Spek({
               describe("Some Feature") {
                   context("calculating whether it is empty") {
                       val str by memoized { "Some string" }
                       it("should be not empty") {
                           expect(str.isEmpty()).toBe(false)
                       }
                   }
               }
           })
```

## Describe the bug
When I use `Spek framework Plugin for Android Studio/IntelliJ IDEA` (plugin - https://plugins.jetbrains.com/plugin/10915-spek-framework, framework - https://github.com/spekframework/spek ) with Atrium library and using only dependency `testImplementation "ch.tutteli.atrium:atrium-fluent-en_GB:0.15.0"` it shows the runtime error during executing unit tests with stack:
```Text
Exception in thread "main" java.util.NoSuchElementException: Could not find any implementation for ch.tutteli.atrium.core.CoreFactory
	at ch.tutteli.atrium.core.polyfills.LoadServiceKt.useSingleService(loadService.kt:30)
	at ch.tutteli.atrium.core.polyfills.LoadServicesKt.loadSingleService(loadServices.kt:21)
	at ch.tutteli.atrium.core.CoreFactoryKt$coreFactory$2.invoke(CoreFactory.kt:22)
	at ch.tutteli.atrium.core.CoreFactoryKt$coreFactory$2.invoke(CoreFactory.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ch.tutteli.atrium.core.CoreFactoryKt.getCoreFactory(CoreFactory.kt)
	at ch.tutteli.atrium.domain.builders.reporting.impl.ObjectFormatterOptionImpl.withDetailedObjectFormatter(ObjectFormatterOptionImpl.kt:13)
	at ch.tutteli.atrium.domain.builders.reporting.impl.DefaultReporterFactory.create(DefaultReporterFactory.kt:29)
	at ch.tutteli.atrium.reporting.ReporterFactoryKt$reporter$2.invoke(ReporterFactory.kt:27)
	at ch.tutteli.atrium.reporting.ReporterFactoryKt$reporter$2.invoke(ReporterFactory.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ch.tutteli.atrium.reporting.ReporterFactoryKt.getReporter(ReporterFactory.kt)
	at ch.tutteli.atrium.creating.impl.RootExpectImpl.<init>(RootExpectImpl.kt:34)
	at ch.tutteli.atrium.creating.RootExpect$Companion.invoke(RootExpect.kt:21)
	at ch.tutteli.atrium.domain.builders.reporting.impl.verb.FinalStepImpl.build(defaultImpls.kt:35)
	at ch.tutteli.atrium.api.verbs.ExpectKt.expect(expect.kt:24)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated$ScratchFileRunnerGenerated.main(tmp.kt:12)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated$ScratchFileRunnerGenerated.generated_get_instance_res0(tmp.kt:165)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated.main(tmp.kt:175)
```
I've found how to fix the issue. I just added extra Atrium dependencies as follows:
```Groovy
    testImplementation "ch.tutteli.atrium:atrium-core-robstoll:${Versions.assertAtrium}"
    testImplementation "ch.tutteli.atrium:atrium-core-robstoll-lib:${Versions.assertAtrium}"
```

It is likely an issue with `Spek framework Plugin for Android Studio/IntelliJ IDEA` (looks like it make a custom class path for all compiled artifacts). Just wanted to get a confirmation for that.

## Expected behaviour
Running Spek tests should work as expected from Android Studio/Intellij IDEA UI interface.

**Comment by robstoll** [comment] 2021-03-02 12:20
@ultraon this rings a bell. I thought spek has fixed this issue by now but apparently not (or a regression). Thanks for sharing the workaround, that's exactly what you need to do. In case someone uses an older version of Atrium, then the following is necessary in addition:
```
testImplementation "ch.tutteli.atrium:atrium-domain-robstoll:${Versions.assertAtrium}"
testImplementation "ch.tutteli.atrium:atrium-domain-robstoll-lib:${Versions.assertAtrium}"
```
Following the thread in slack which discussed this problem beforehand:
https://kotlinlang.slack.com/archives/C0BE6KSRW/p1593680326029800

The good news, Atrium will no longer use ServiceLoader starting from 0.16.0 (currently in the making) and thus the problem should then disappear even if if no fix for spek is provided.

Since I won't fix something, I am going to close this issue. Thanks for the report though, could be helpful for others.

**Closed by robstoll** 2021-03-02 12:20 UTC
Labels: bug

**Comment by ultraon** [comment] 2021-03-02 12:24
Thank you very much! You provided pretty good details for deep understanding!
